import React from "react";
import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMnHSq21jDWrE1yjaElJ5di8gTljEmm8pqvQ&usqp=CAU",
    title: "Tsehay Taye",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW4CVufwzDWh-mc7T275u4mQqhX-q6jLPUeA&usqp=CAU",
    title: "Melat Zewdu",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP9vTGooygiJamDEa1B0L7oxXu9k5UA4lqsEly6n4HQTGRrN8ZzpY7hN3LD8UeLKfZpY8&usqp=CAU",
    title: "Daniel Kiflu",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlrRJB1hDYz5l5znmZjYmTymCNMH22CIeBXA&usqp=CAU",
    title: "Abenezer Moges",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5Qi8Pjc5wm_Jg5nBTtvbPkqFoieOdGKGjLg&usqp=CAU",
    title: "Tadesse Gebru",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKIzJSFihJTk7zBzdcWLsRGLhs7YSZc44kcw&usqp=CAU",
    title: "Freiya Solomon",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://media.afrocharts.com/file/afrocharts-media/uploads/2023/2/photo-2023-02-04-21-33-01-afrocharts-63e7a8d964f8ac1f934cbaf.jpg",
    title: "Abel Mamo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPfzFnwctTdQm5nV24lXMqMLlzAFe1gBqq9950URB3bKMXq-wlzOHLTSZv_ixcgWWzCN8&usqp=CAU",
    title: "Melat Zeru",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://static6.tgstat.ru/channels/_0/17/1730289427cf919a00b7891fbef1afc0.jpg",
    title: "Hannan Tarik",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlip7DxeWJWL1ktx46K76RoyXeJzqvT6P6Zw&usqp=CAU",
    title: "Selam Tefera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGZpW-LdX64AJ27Pn81PTAOskFzxIF6JxiWA&usqp=CAU",
    title: "Biruk Fitsum",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsNKKMNsl5Qg2-wg-OT1o_7_0c_FXOwihdKA&usqp=CAU",
    title: "Yosef Amare",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://miro.medium.com/v2/resize:fit:480/1*lV2I2QtKtf89CILGC3OL4Q.jpeg",
    title: "Danawit Ebsa",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4BsPtNSRQFjKvkpci6UywUXB2iLEAfK8TRzyC7iht5JvrMSWmRGlZ2WZFuk1KustLUtM&usqp=CAU",
    title: "Jalene Boru",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT5H0iTddvH2E9q_sjbuYw042ltAIWsu71Eg&usqp=CAU",
    title: "Yabsira Tamru",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
    
];

export default data;
